# Generated by Django 5.2.8 on 2025-11-28 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('iso', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('short', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gloss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('transcriptions', models.JSONField(default=list)),
                ('clarifies_usage', models.ManyToManyField(blank=True, related_name='usage_of_clarified', to='cms.gloss')),
                ('collocations', models.ManyToManyField(blank=True, to='cms.gloss')),
                ('contains', models.ManyToManyField(blank=True, related_name='contained_by', to='cms.gloss')),
                ('near_homophones', models.ManyToManyField(blank=True, to='cms.gloss')),
                ('near_synonyms', models.ManyToManyField(blank=True, to='cms.gloss')),
                ('to_be_differentiated_from', models.ManyToManyField(blank=True, to='cms.gloss')),
                ('translations', models.ManyToManyField(blank=True, to='cms.gloss')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.language')),
            ],
            options={
                'unique_together': {('content', 'language')},
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('show_before_solution', models.BooleanField(default=False)),
                ('gloss', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cms.gloss')),
            ],
        ),
        migrations.CreateModel(
            name='Situation',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('glosses', models.ManyToManyField(blank=True, related_name='relevant_in_situations', to='cms.gloss')),
            ],
        ),
        migrations.CreateModel(
            name='SpecificSituation',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('image_link', models.URLField(blank=True, null=True)),
                ('descriptions', models.ManyToManyField(blank=True, related_name='describes_specific_situations', to='cms.gloss')),
                ('glosses', models.ManyToManyField(blank=True, related_name='relevant_in_specific_situations', to='cms.gloss')),
                ('native_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='native_specific_situations', to='cms.language')),
                ('target_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_specific_situations', to='cms.language')),
            ],
        ),
    ]
