# Generated by Django 5.2.8 on 2025-11-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='language',
            name='ai_note',
            field=models.TextField(blank=True),
        ),
    ]
