# Generated by Django 5.2.8 on 2025-11-28 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_language_ai_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='situation',
            name='descriptions',
            field=models.ManyToManyField(blank=True, related_name='describes_situations', to='cms.gloss'),
        ),
        migrations.AddField(
            model_name='situation',
            name='image_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='SpecificSituation',
        ),
    ]
