# Generated by Django 5.2.8 on 2025-11-29 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_situation_descriptions_situation_image_link_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
    ]
